### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by cperryk** [micnews/html-word-count#5]
Hey @iefserge — Thanks for this repo. Do you plan on updating it? Noticed that one of the deps, `html-to-text`, is two major versions out of date, and I'm getting a bug because of it. Happy to help maintain the repo if you'd like to name me a collaborator.

**Comment by iefserge** [comment]
@cperryk yes, but I haven't looked at the changelog in case there are API changes, pull requests are welcome!

**Comment by cperryk** [comment]
@iefserge Thanks! Just submitted a PR: https://github.com/micnews/html-word-count/pull/6 The only relevant change I see in the dep updates is in html-to-text increasing the min Node version to 0.10.0. That PR patches the version number -- not sure if you want to bump the major version of this because of that, but let me know and I'll update.

**Comment by iefserge** [comment]
@cperryk It should probably be fine to release it as a patch, but I'm gonna bump major because of node.js version requirement.
Thanks!
